import{Song} from './interfaces/cancionDetalles';

export const SONGS : Song[] = [
  {track: 1, title: "Blues for 3+1", composer: ["Jimmy Smith"], performer: ["Jimmy Smith"], time:"04:53", year:"1972",album:1},
  {track: 2, title: "Ode to Billie Joe", composer: ["Bobbie Gentry"], performer: ["Jimmy Smith"], time:"06:21", year: "1969", album:1},
  {track: 3, title: "Organ Grinder's Swing",	composer: ["Will Hudson", "Irving Mills", "Mitchell Parish"], performer: ["Jimmy Smith"], time:"02:13", year: "1965", album:1},
  {track: 4,	title: "Ape Woman", composer:	["Lalo Schifrin"], performer: ["Jimmy Smith"],  time:"03:22", year: "1963", album:1},
  {track: 5, title: "(I Can't Get No) Satisfaction", composer:["Mick Jagger", "Keith Richards"], performer: ["Jimmy Smith"],  time:"04:23", year: "1969", album:1},
  {track: 6, title: "Funky Broadway", composer: ['Arlester "Dyke" Christian'], performer: ["Jimmy Smith"],  time:"06:39", year: "1967", album:1},
  {track: 7, title: "Mellow Mood", composer: ["Jimmy Smith"], performer: ["Jimmy Smith"],  time:"08:40", year: "1969", album:1},
  {track: 8, title: "Burning Spear",	composer: ["Richard Evans"], performer: ["Jimmy Smith"],  time:"02:54", year: "1969", album:1},
  {track: 9,	title: "One Mint Julep", composer: ["Rudy Toombs"], performer: ["Jimmy Smith"],  time:"05:28", year: "1967", album:1},
  {track:10, title: "Hobo Flats", composer: ["Oliver Nelson"], performer: ["Jimmy Smith"],  time:"04:42", year: "1963", album:1},
  {track: 11,	title: "Groove Drops",	composer: ["Jimmy Smith"], performer: ["Jimmy Smith"],  time:"04:12", year: "1969", album:1},
  {track: 12,	title: "TNT", composer:["Grady Tate", "Ben Tucker"], performer: ["Jimmy Smith"],  time:"05:24", year: "1967", album:1},
  {track: 13,	title: "Blues in the Night", composer:["Harold Arlen", "Johnny Mercer"], performer: ["Jimmy Smith"],  time:"04:43", year: "1964", album:1},
  {track: 14,	title: "The Sermon", composer: ["Jimmy Smith"], performer: ["Jimmy Smith"],  time:"07:41", year: "1958", album:1},
  {album:2, track: 1,	title: "All Tomorrow's Parties", composer:["Lou Reed"],	performer: ["The Velvet Underground"], year: "1966", time:""},
  {album:2, track: 2,	title: "Sunday Morning", composer:["John Cale", "Lou Reed"],	performer: ["The Velvet Underground"], year: "1966", time:"",},
  {album:2, track: 3, title: "I'm Waiting for the Man", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 4, title: "Femme Fatale", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 5, title: "Venus in Furs", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 6, title: "Run Run Run", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 7, title: "All Tomorrow's Parties", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 8, title: "Heroin", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 9, title: "There She Goes Again", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 10, title: "I'll Be Your Mirror", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 11, title: "The Black Angel's Death Song", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 12, title: "European Son", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 13, title: "Melody Laughter", composer: ["	John Cale","Sterling Morrison","Nico","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 14, title: "It Was a Pleasure Then", composer: ["John Cale", "Nico", "Lou Reed"],	performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:2, track: 15, title: "Chelsea Girls", composer:["Sterling Morrison", "Lou Reed"],	performer: ["The Velvet Underground"], year: "1966", time:"", },
  {album:3, track: 1, title: "There Is No Reason", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 2, title: "Sheltered Life", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 3, title: "It's All Right (The Way That You Live)", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 4, title: "I'm Not Too Sorry (Now That You're Gone)", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 5, title: "Here She Comes Now", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 6, title: "Guess I'm Falling in Love", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:"" },
  {album:3, track: 7, title: "Booker T.", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:""},
  {album:3, track: 8, title: "White Light/White Heat", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 9, title: "The Gift", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:""},
  {album:3, track: 10, title: "Lady Godiva's Operation", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 11, title: "Here She Comes Now", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:""},
  {album:3, track: 12, title: "I Heard Her Call My Name", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:""},
  {album:3, track: 13, title: "Sister Ray", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:""},
  {album:3, track: 14, title: "Stephanie Says", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 15, title: "Temptation Inside Your Heart", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:3, track: 16, title: "Hey Mr. Rain", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1967", time:"", },
  {album:4, track: 1, title: "What Goes On", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 2, title: "Candy Says", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 3, title:	"What Goes On", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 4, title:	"Some Kinda Love", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 5, title:	"Pale Blue Eyes", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 6, title:	"Jesus", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 7, title:	"Beginning to See the Light", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 8, title:	"I'm Set Free", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 9, title:	"That's the Story of My Life", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 10, title:	"The Murder Mystery", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 11, title:	"After Hours", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 12, title:	"Foggy Notion", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Hy Weiss","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 13, title:	"I Can't Stand It", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 14, title:	"I'm Sticking With You", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 15, title:	"One of These Days", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 16, title:	"Lisa Says", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 17, title:	"It's Just Too Much", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:4, track: 18, title:	"Countess from Hong Kong", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 1, title: "Who Loves the Sun", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1970", time:"", },
  {album:5, track: 2, title: "Sweet Jane", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 3, title: "Rock & Roll", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 4,	title: "Cool It Down", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 5, title: "New Age", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 6, title: "Head Held High", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 7, title: "Lonesome Cowboy Bill", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 8, title: "I Found a Reason", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 9, title: "Train Round the Bend", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 10, title: "Oh! Sweet Nuthin'", composer: ["Sterling Morrison","Lou Reed","Moe Tucker","Doug Yule"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 11, title: "Satellite of Love", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 12, title: "Walk and Talk It", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 13, title: "Oh Gin", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 14, title: "Sad Song", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 15, title: "Ocean", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 16, title: "Ride into the Sun", composer: ["John Cale","Sterling Morrison","Lou Reed","Moe Tucker"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 17, title: "Some Kinda Love", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 18, title: "I'll Be Your Mirror", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:5, track: 19, title: "I Love You", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1969", time:"", },
  {album:6, track: 1, title: "Venus in Furs", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:6, track: 2, title: "Prominent Men", composer: ["John Cale","Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:6, track: 3, title: "Heroin", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:6, track: 4, title: "I'm Waiting for the Man", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:6, track: 5, title: "Wrap Your Troubles in Dreams", composer: ["Harry Barris","Billy Moll","Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:6, track: 6, title: "All Tomorrow's Parties", composer: ["Lou Reed"], performer: ["The Velvet Underground"], year: "1965", time:"", },
  {album:7, track: 1, title: "Starboy", composer: ["The Weeknd","Daft Punk"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 2, title: "Party Monster", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 3, title: "False Alarm", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 4, title: "Reminder", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 5, title: "Rockin’", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 6, title: "Secrets", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 7, title: "True Colors", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 8, title: "Stargirl Interlude", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 9, title: "Sidewalks", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 10, title: "Six Feet Under", composer: ["he Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 11, title: "Love To Lay", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 12, title: "A Lonely Night", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 13, title: "Attention", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 14, title: "Ordinary Life", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 15, title: "Nothing Without You", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 16, title: "All I Know", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 17, title: "Die For You", composer: ["The Weeknd"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:7, track: 18, title: "I Feel It Coming", composer: ["The Weeknd"," Daft Punk"], performer: ["The Weeknd"], year: "2016", time: "", },
  {album:8, track: 1, title: "Ritmo	Black Eyed Peas", composer: ["Black Eyed Peas"], performer: ["J Balvin", "Jade Smith"], year: "2020", time: "", },
  {album:8, track: 2, title: "Feel The Beat", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","Maluma"], year: "2020", time: "", },
  {album:8, track: 3, title: "Mamacita", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 4, title: "Girl Like Me", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","Shakira"], year: "2020", time: "", },
  {album:8, track: 5, title: "Vida Loca", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","Nicky Jam","Tyga"], year: "2020", time: "", },
  {album:8, track: 6, title: "No Manana", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","El Alfa"], year: "2020", time: "", },
  {album:8, track: 7, title: "Tonta Love", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 8, title: "Celebrate", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 9, title: "Todo Bueno", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","Piso"], year: "2020", time: "", },
  {album:8, track: 10, title: "Duro Hard", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","Becky G"], year: "2020", time: "", },
  {album:8, track: 11, title: "Mabuti", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas","French Montana"], year: "2020", time: "", },
  {album:8, track: 12, title: "I Woke Up", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 13, title: "Get Loose Now", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 14, title: "Action", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
  {album:8, track: 15, title: "News Today", composer: ["Black Eyed Peas"], performer: ["Black Eyed Peas"], year: "2020", time: "", },
]
